### ISSUE TITLE
Add contact email

### ISSUE THREAD

**Issue by BenJam** [numfocus/projects-director#2]
`/projects-director/project-briefs/sustainability-index.html#how-to-get-involved`

> To get involved, drop me an email and let me know what you’d like to help with and what your availability is like.

No email link.

**Comment by BenJam** [comment]
I'm leaving this because we should work together. I'm working on Libraries.io with @andrew. We just released metadata on ~25m OSS projects for this kind of purpose.

**Comment by christi3k** [comment]
Thanks for getting in touch @BenJam and reminding me I needed to add a contact email to the SI project brief. Let's chat soon!
