### ISSUE TITLE
Table renders as HTML text rather than table

### ISSUE THREAD

**Issue by gvwilson** [numfocus/projects-director#3]
On <https://numfocus.github.io/projects-director/project-briefs/infrastructure-proposal.html>, under the heading "Capabilities of current vs. proposed resources", the table appears as HTML text rather than as a table.

**Comment by christi3k** [comment]
Evidently I have forgotten how to write html! And, it turns out GitHub markdown rendering is happy when colspan values are not enclosed by quotes by GitHub pages rendering is not. Fixed now. 

Thanks for reporting @gvwilson!
